version: "3.9"

services:
  fintech-platform-web:
    build: .
    container_name: paybrodge-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # helps live reload in Docker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
