version: "3.9"

services:
  paybridge-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: paybridge-web
    ports:
      - "3000:80"
    networks:
      - paybridge_network
    restart: unless-stopped

networks:
  paybridge_network:
    external: true